# enable italics for comments
set -g default-terminal "tmux-256color"

# set fish shell as default
set -g default-shell /usr/bin/fish
set -g default-command /usr/bin/fish

# Enable mouse support including scrolling
set -g mouse on

# for images in nvim
set -gq allow-passthrough on
set -g visual-activity off

# reset windows numbers when one is closed
set -g renumber-windows on


# enable C-Enter in neovim
set -s extended-keys on
set -as terminal-features 'ghostty:extkeys'
set -s extended-keys-format csi-u

# tmux fzf config
TMUX_FZF_PANE_FORMAT="[#{window_name}] #{pane_current_command}  [#{pane_width}x#{pane_height}] #{?pane_active,[active],[inactive]}"

# TMUX plugin manager (keep this line at the very bottom of tmux.conf)
set -g @tpm_plugin 'tmux-plugins/tpm'
set -g @tpm_plugin 'sainnhe/tmux-fzf'
run '~/.tmux/plugins/tpm/tpm'
